disabled_rules:
  - compiler_protocol_init
  - control_statement
  - cyclomatic_complexity
  - file_length
  - identifier_name
  - shorthand_operator
  - force_cast
  - function_parameter_count
  - line_length
  - trailing_newline
  - statement_position
  - syntactic_sugar
  - unneeded_break_in_switch
  - unction_body_length
  - multiple_closures_with_trailing_closure
  - function_body_length
  - todo
  - type_body_length

excluded:
  - Pods
