disabled_rules:
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - cyclomatic_complexity
  - file_length
  - identifier_name
  - opening_brace
  - return_arrow_whitespace
  - shorthand_operator
  - force_cast
  - mark
  - function_parameter_count
  - line_length
  - vertical_whitespace
  - trailing_whitespace
  - trailing_newline
  - trailing_semicolon
  - statement_position
  - syntactic_sugar
  - unneeded_break_in_switch
  - unction_body_length
  - multiple_closures_with_trailing_closure
  - unused_closure_parameter
  - for_where
  - function_body_length
  - leading_whitespace
  - todo
  - type_body_length
  - private_over_fileprivate
  
excluded:
  - Pods
